// Cytosim was created by Francois Nedelec. Copyright 2021 Cambridge University.
/**
 This program exports simulation objects, in a compact binary format that
 is more efficient than the text files generated by 'report'.
 The system is exported using two files:
 
 1. a file containing coordinates of the objects, aka. `the vector file`
    This is a binary file stored either in floating point or fixed point:
    'NAME.float32' : [ 4 bytes, a floating point in micrometers ]
    'NAME.fixed16' : [ 2 bytes, an int16 = 2048 * micrometer ],

 2. a file describing the objects: 'NAME.paths32'
    This is a binary file containing uniform records consisting of:
     [4 bytes, uint32: class]
     [4 bytes, uint32: identity]
     [4 bytes, uint32: first index in the vector file]
     [4 bytes, uint32: last index in the vector file]

 Two files are generated for each timepoint of the trajectory file.
 The 'NAME' would typically be 'cell0000' or alike.
 
 FJN, 2--4 June 2021
*/

#include <fstream>
#include "filepath.h"
#include "frame_reader.h"
#include "iowrapper.h"
#include "glossary.h"
#include "simul.h"


void help(std::ostream& os)
{
    os << "This program exports simulation objects, in a compact binary format that\n";
    os << "is more efficient than the text files generated by 'report'.\n";
    os << "The system is exported using two files:\n";
    
    os << "1. a file containing coordinates of the objects, aka. `the vector file`'\n";
    os << "   This is a binary file stored either in floating point or fixed point:\n";
    os << "   'NAME.float32' : [ 4 bytes, a floating point in micrometers ]\n";
    os << "   'NAME.fixed16' : [ 4 bytes, an int32 = 2048 * micrometer ],\n";

    os << "2. a file describing the objects: 'NAME.paths32'\n";
    os << "   This is a binary file containing uniform records consisting of:\n";
    os << "    [4 bytes, uint32: class]\n";
    os << "    [4 bytes, uint32: identity]\n";
    os << "    [4 bytes, uint32: first index in the vector file]\n";
    os << "    [4 bytes, uint32: last index in the vector file]\n";

    os << "Two files are generated for each timepoint of the trajectory file.\n";
    os << "The 'NAME' would typically be 'cell0000' or alike.\n";
    os << "Made with format version " << Simul::currentFormatID << " and DIM=" << DIM << "\n";
}

//------------------------------------------------------------------------------
#pragma mark - Globals

FILE* fileP = nullptr;
FILE* fileS = nullptr;

int use_fixed16 = 0;
size_t pointer = 0;
size_t overflow = 0;

//------------------------------------------------------------------------------
#pragma mark - Files

FILE * openFile(const char name[], bool binary)
{
    FILE * f = nullptr;
    
    if ( binary )
        f = fopen(name, "wb");
    else
        f = fopen(name, "w");
    if ( !f )
        std::cerr << "Error: could not create `" << name << "'\n";
    if ( f && ferror(f) )
    {
        fclose(f);
        std::cerr << "Error making `" << name << "'\n";
        f = nullptr;
    }
    return f;
}

bool openFiles(const char root[], unsigned frm)
{
    char str[512] = { 0 };
    pointer = 0;
    if ( use_fixed16 )
        snprintf(str, sizeof(str), "%s%04u.fixed16", root, frm);
    else
        snprintf(str, sizeof(str), "%s%04u.float32", root, frm);
    fileP = openFile(str, true);
    
    snprintf(str, sizeof(str), "%s%04u.paths32", root, frm);
    fileS = openFile(str, true);
    return ( fileP && fileS );
}

void closeFiles()
{
    fclose(fileP); fileP = nullptr;
    fclose(fileS); fileS = nullptr;
}

//------------------------------------------------------------------------------
#pragma mark - data write

int16_t fix(real x)
{
    constexpr real SCALE = 2048;
    long l = std::lround(SCALE*x);
    int16_t i = (int16_t)l;
    overflow += ( l != (long)i );
    //if ( l != (long)i ) fprintf(stderr, "fixed16 overflow %f %li\n", x, l);
    return i;
}

void writeScalar16(real alpha)
{
    int16_t i = fix(alpha);
    fwrite(&i, 1, sizeof(int16_t), fileP);
    ++pointer;
}

void writeScalar32(real alpha)
{
    float x = alpha;
    fwrite(&x, 1, sizeof(float), fileP);
    ++pointer;
}

void writeVector16(Vector2 const& pos)
{
    int16_t vec[2] = { fix(pos.XX), fix(pos.YY) };
    fwrite(vec, 2, sizeof(int16_t), fileP);
    pointer += 2;
}

void writeVector32(Vector2 const& pos)
{
    float vec[2] = { (float)pos.XX, (float)pos.YY };
    fwrite(vec, 2, sizeof(float), fileP);
    pointer += 2;
}

void writeVector16(Vector3 const& pos)
{
    int16_t vec[3] = { fix(pos.XX), fix(pos.YY), fix(pos.ZZ) };
    fwrite(vec, 3, sizeof(int16_t), fileP);
    pointer += 3;
}

void writeVector32(Vector3 const& pos)
{
    float vec[3] = { (float)pos.XX, (float)pos.YY, (float)pos.ZZ };
    fwrite(vec, 3, sizeof(float), fileP);
    pointer += 3;
}

void writeObject(uint32_t a, uint32_t b, size_t s, size_t p)
{
    uint32_t c = (uint32_t)s;
    uint32_t d = (uint32_t)(p-DIM);
    if ( c != (size_t)s )
        fprintf(stderr, "unint32 index overflow!\n");
    fwrite(&a, 4, 1, fileS);
    fwrite(&b, 4, 1, fileS);
    fwrite(&c, 4, 1, fileS);
    fwrite(&d, 4, 1, fileS);
}

//------------------------------------------------------------------------------
#pragma mark - Export

template < void writeVector(Vector const&) >
void writeFibers(FiberSet const& set)
{
    // process fibers in the natural order:
    for ( Fiber const* obj = set.firstID(); obj; obj = set.nextID(obj) )
    {
        size_t start = pointer;
        for ( size_t i = 0; i < obj->nbPoints(); ++i )
            writeVector(obj->posPoint(i));
        
        writeObject(obj->prop->number(), obj->identity(), start, pointer);
    }
}

template < void writeVector(Vector const&), void writeScalar(real) >
void writeSolids(SolidSet const& set)
{
    for ( Solid const* obj = set.firstID(); obj; obj = set.nextID(obj) )
    {
        for ( size_t i = 0; i < obj->nbPoints(); ++i )
        {
            size_t start = pointer;
            writeVector(obj->posPoint(i));
            writeScalar(obj->radius(i));
            writeObject(obj->prop->number(), obj->identity(), start, pointer);
        }
    }
}

template < void writeVector(Vector const&), void writeScalar(real) >
void writeBeads(BeadSet const& set)
{
    for ( Bead const* obj = set.firstID(); obj; obj = set.nextID(obj) )
    {
        size_t start = pointer;
        writeVector(obj->posPoint(0));
        writeScalar(obj->radius());
        writeObject(obj->prop->number(), obj->identity(), start, pointer);
    }
}

template < void writeVector(Vector const&), void writeScalar(real) >
void writeSpheres(SphereSet const& set)
{
    for ( Sphere const* obj = set.firstID(); obj; obj = set.nextID(obj) )
    {
        size_t start = pointer;
        writeVector(obj->posPoint(0));
        writeScalar(obj->radius());
        writeObject(obj->prop->number(), obj->identity(), start, pointer);
    }
}

//------------------------------------------------------------------------------
#pragma mark -

int main(int argc, char* argv[])
{
    if ( argc > 1 && strstr(argv[1], "help") )
    {
        help(std::cout);
        return EXIT_SUCCESS;
    }
    Simul simul;
    Glossary arg;
    FrameReader reader;
    
    if ( arg.read_strings(argc-1, argv+1) )
        return EXIT_FAILURE;
    
    if ( arg.has_key("directory") )
        FilePath::change_dir(arg.value("directory"));

    arg.set(use_fixed16, "fixed");
    
    std::string input = Simul::TRAJECTORY;
    arg.set(input, ".cmo") || arg.set(input, "input");
    reader.openFile(input);
    
    if ( reader.badFile() )
    {
        fprintf(stderr, "could not open input file\n");
        return EXIT_FAILURE;
    }
    
    try
    {
        unsigned frm = 0;
        simul.loadProperties();
        // process all frames of the trajectory:
        while ( 0 == reader.loadNextFrame(simul) )
        {
            if ( openFiles("cell", frm) )
            {
                if ( use_fixed16 )
                {
                    overflow = 0;
                    writeFibers<writeVector16>(simul.fibers);
                    writeSpheres<writeVector16, writeScalar16>(simul.spheres);
                    writeSolids<writeVector16, writeScalar16>(simul.solids);
                    writeBeads<writeVector16, writeScalar16>(simul.beads);
                    if ( overflow )
                        fprintf(stderr, "Warning: fixed16 data format overflowed %lu times\n", overflow);
                }
                else
                {
                    writeFibers<writeVector32>(simul.fibers);
                    writeSpheres<writeVector32, writeScalar32>(simul.spheres);
                    writeSolids<writeVector32, writeScalar32>(simul.solids);
                    writeBeads<writeVector32, writeScalar32>(simul.beads);
                }
                closeFiles();
            }
            ++frm;
        }
    }
    catch( Exception & e )
    {
        std::cerr << e.brief() << '\n';
        return EXIT_FAILURE;
    }
}
