[project]
authors = ["oakenuwa <hakenuwa@ucsd.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "analysis-code"
platforms = ["linux-64","osx-arm64"]
version = "0.1.0"

[tasks]
makeplot = "python3 analysis-codes/make_boxplots-copy.py"
extractcoords = "python3 analysis-codes/extract_space.py"
extension = "python3 analysis-codes/membrane_extension_calculator.py"
protocell = "python3 ../protocell-contact-probe.py"
makeProtoPlot = "python ../protocell-contact-probe.py --plot"

[dependencies]
python = ">=3.12.8,<3.14"

[pypi-dependencies]
automembrane = { git = "https://git@github.com/ctleelab/automembrane.git", rev = "cfaa9b5afff47e672e6d1e21b52999ea20662017"}
ctleelab_plothelper = { git = "https://github.com/ctleelab/ctleelab-mpl-utilities.git", branch = "development"}
