#!/usr/bin/env python3
#
# fig_platelet.py
#
# simple extraction of data from files
#
# Copyright F. Nedelec, 20.11.2018

"""
    Assembles different data into single plot, for platelet simulations
    Plot the data contained in 'scaling.txt' in different directories

Syntax:

    fig_platelet.py DIRECTORIES

Description:

    This script is used to analyze platelet simulations

F. Nedelec, 20 November 2018
"""

import sys, os, subprocess, math
import matplotlib.pyplot as plt
from pyned import uncode, format_line, power_fit, powerlaw_fit, frange

title = os.path.basename(os.getcwd())

#------------------------------------------------------------------------

def next_power_of_2(x):
    return 1 if x == 0 else 2**math.ceil(math.log2(x))


def plot_data(ax, data, col):
    # plot data:
    for x, y in data:
        ax.plot(x, y, 'o', markersize=4, markerfacecolor=col, markeredgewidth=0, markeredgecolor='None', alpha=0.5)
    bot, top = ax.get_ylim()
    # add bestfit powerlaw with different offsets:
    for base in [ 0 ]:
        [ scale, power ] = powerlaw_fit([(x, y-base) for x,y in data])
        X = frange(4, 18, 100)
        Y = [ base + scale*(x**power) for x in X ]
        ax.plot(X, Y, '-', color=col, linewidth=0.5, alpha=0.5)
        msg = "fit %.2f + %.3f * ( R^ %.3f )" % (base, scale, power)
        print(msg)
    #plt.text(4, top, msg, fontsize=6)

    
#------------------------------------------------------------------------

def process(ax, path, filename, color):
    """ 
        This extracts parameters from the specified file, generated by
        get_platelet.py run???? > scaling.txt
    """
    os.chdir(path)
    if not os.path.isfile(filename):
        sys.stderr.write("  missing file `%s/%s'\n" % (path, filename))
    data = []
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line[0]=='%':
                continue
            d = [ float(x) for x in uncode(line).split() ]
            if len(d) > 2:
                data.append((2*math.pi*d[1], d[8]))
    plot_data(ax, data, color)


#------------------------------------------------------------------------

def main(args):
    paths = []
    for arg in args:
        if os.path.isdir(arg):
            paths.append(arg)
        else:
            sys.stderr.write("  Error: unexpected argument `%s'\n" % arg)
            sys.exit()
    if not paths:
        paths = ['.']
    # create figure:
    fig, ax = plt.subplots()
    cdir = os.getcwd()
    colors = ['blue', 'black', 'red', 'purple', 'green', 'yellow', 'orange', 'mustard', 'gray', 'pink']
    for i, p in enumerate(paths):
        sys.stdout.write('----- '+p+"\n")
        os.chdir(cdir)
        process(ax, p, 'scaling.txt', colors[i])
    os.chdir(cdir)
    # complete figure:
    #ax.set_xlim(0, 18)
    ax.set_xlabel(r'Platelet size 2PI.R ($\mu m$)')
    lim = 1000*math.ceil(ax.get_ylim()[1]/1000)
    ax.set_ylim(0, lim)
    ax.set_ylabel('Radial push (pN)')
    ax.set_title('Platelet scaling')
    fig.savefig('fig.pdf', dpi=300)
    plt.close()

#------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1].endswith("help"):
        print(__doc__)
    else:
        main(sys.argv[1:])

