#!/usr/bin/env python3
#
# plot_platelet.py
#
# simple extraction of data from files
#
# Copyright F. Nedelec, 2011 - 14.11.2018

"""
    Make plot in given run directories, for platelet simulations
    Plot the data contained in 'platelet.txt' as a function of time

Syntax:

    plot_platelet.py DIRECTORIES
    
Example:

    plot_platelet.py run???? > data.txt

Description:

    This script is used to analyze platelet simulations

F. Nedelec, July 2017 -- December 2018
"""

import sys, os, subprocess, math
import statistics
import matplotlib.pyplot as plt
from pyned import uncode, format_line, power_fit, powerlaw_fit, frange

title = os.path.basename(os.getcwd())

#------------------------------------------------------------------------

def next_power_of_2(x):
    return 1 if x == 0 else 2**math.ceil(math.log2(x))


def plot_data(xdata, ydata, ylabel):
    fig, ax = plt.subplots()
    ax.plot(xdata, ydata, color=[0,0,0.7], linewidth=1.0)
    # add mean:
    if ydata:
        L, R = ax.get_xlim()
        M = sum(ydata) / len(ydata)
        ax.plot([0, R], [M, M], '-', color='blue', linewidth=0.5, alpha=0.5)
        sys.stdout.write('%s : mean = %.2f \n' % (ylabel, M))
        M = statistics.median(ydata)
        ax.plot([0, R], [M, M], '-', color='black', linewidth=0.5, alpha=0.5)
        ax.set_xlim([0, R])
    S = next_power_of_2(ax.get_ylim()[1])
    ax.set_ylim([0, S])
    ax.set_xlabel('time (s)')
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    fig.savefig('p-'+ylabel.split()[0]+'.png', dpi=100)
    plt.close()


def make_plots(arg):
    """
    % nb_fiber   polymer   tension     force    length    radius
            20   113.440  -375.708  2967.984     8.192     1.275
    """
    T = [ d[0] for d in arg ]
    plot_data(T, [ d[1] for d in arg ], 'nb-microtubules')
    plot_data(T, [ d[2] for d in arg ], r'total-polymer ($\mu m$)')
    plot_data(T, [-d[3] for d in arg ], 'ring-tension (pN)')
    plot_data(T, [ d[4] for d in arg ], 'radial-force (pN)')
    plot_data(T, [ d[5] for d in arg ], r'ring-length ($\mu m$)')
    plot_data(T, [ d[6] for d in arg ], r'ring-radius ($\mu m$)')

    
#------------------------------------------------------------------------

def process(path, filename):
    """ 
        This extracts parameters from 'platelet.txt', generated by
        report time platelet verbose=0 > platelet.txt
    """
    os.chdir(path)
    if not os.path.isfile(filename):
        subprocess.call(['report3', 'time', 'platelet', 'verbose=0'], stdout=open(filename, 'w'))
    if not os.path.isfile(filename):
        sys.stderr.write("  missing file `%s/%s'\n" % (path, filename))
    data = []
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line[0]=='%':
                d = [ float(x) for x in uncode(line).split() ]
                if len(d) > 2:
                    data.append(d)
    make_plots(data)


#------------------------------------------------------------------------

def main(args):
    paths = []
    global title
    for arg in args:
        if os.path.isdir(arg):
            paths.append(arg)
        else:
            sys.stderr.write("  Error: unexpected argument `%s'\n" % arg)
            #sys.exit()
    if not paths:
        paths = ['.']
    cdir = os.getcwd()
    for p in paths:
        sys.stdout.write('----- '+p+"\n")
        os.chdir(cdir)
        title = p
        process(p, 'platelet.txt')
    os.chdir(cdir)

#------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1].endswith("help"):
        print(__doc__)
    else:
        main(sys.argv[1:])

