#!/usr/bin/env python3
#
# steady_platelet.py
#
# simple extraction of data from files
#
# Copyright F. Nedelec, 2011 - 29.11.2018

"""
    Make plot in given run directories, for platelet simulations
    Plot the data contained in 'platelet.txt' as a function of time

Syntax:

    steady_platelet.py DIRECTORIES
    
Description:

    This script is used to analyze platelet simulations

F. Nedelec, July 2017 -- November 2018
"""

import sys, os, subprocess, math
import statistics
import matplotlib.pyplot as plt
from pyned import uncode, format_line, power_fit, powerlaw_fit, frange

title = os.path.basename(os.getcwd())

#------------------------------------------------------------------------


def plot_data(ax, data, col):
    # plot data:
    x, y = zip(*data)
    ax.plot(x, y, '-', color=col, linewidth=2)
    # add mean:
    if y:
        avg = sum(y)/len(y)
        ax.plot([min(x), max(x)], [avg, avg], '-', color=col, linewidth=1, alpha=0.5)
        msg = " > mean force (column 4) %.3f" % avg
        print(msg)
        #plt.text(4, top, msg, fontsize=6)


#------------------------------------------------------------------------

def process(ax, filename, color):
    """ 
        This extracts values from files 'platelet.txt', generated by
        report time platelet verbose=0 > platelet.txt
    """
    if not os.path.isfile(filename):
        sys.stderr.write("  missing file `%s/%s'\n" % (path, filename))
    data = []
    with open(filename, 'r') as f:
        avg = 0
        cnt = 0
        for line in f:
            line = line.strip()
        if not line or line[0]=='%':
            continue
        d = [ float(x) for x in uncode(line).split() ]
        if len(d) > 2:
            data.append((d[0], d[4]))
            if d[0] > 250:
                avg = avg + d[1]
                cnt = cnt + 1
        print(" > mean number of microtubules (column 1) %.3f" % (avg/cnt))
    plot_data(ax, data, color)


#------------------------------------------------------------------------

def main(args):
    paths = []
    for arg in args:
        if os.path.isdir(arg):
            paths.append(arg)
        else:
            sys.stderr.write("  Error: unexpected argument `%s'\n" % arg)
            sys.exit()
    if not paths:
        paths = ['.']
    # create figure:
    fig, ax = plt.subplots()
    colors = ['blue', 'black', 'red', 'purple', 'green', 'yellow', 'orange', 'brown']
    for i, p in enumerate(paths):
        sys.stdout.write('----- '+p+"\n")
        process(ax, p+'/platelet.txt', colors[i])
    # complete figure:
    #ax.set_xlim(0, 18)
    ax.set_xlabel('Time (s)')
    ax.set_ylim(0, 10000)
    ax.set_ylabel('Radial push (pN)')
    #ax.set_title('Force')
    fig.savefig('steady.pdf', dpi=300)
    plt.close()

#------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1].endswith("help"):
        print(__doc__)
    else:
        main(sys.argv[1:])

