// Cytosim was created by Francois Nedelec. Copyright 2007-2017 EMBL.
/**
 This is a program to export simulation objects, in a compact format that
 is more efficient than the text files generated by 'report'.
 The binary data follows the `Sweet20` layout:
 
     [2 bytes, unsigned integer: class]
     [2 bytes, unsigned integer: info/color]
     [4 bytes, unsigned integer: identity]
     [4 bytes, float: X coordinate]
     [4 bytes, float: Y coordinate]
     [4 bytes, float: Z coordinate]

 One file is generated for each timepoint of the trajectory file.
 If `binary=0` is specificed, the same data is written as ASCII text.
 
 FJN, 20.11.2020, 21.11.2020
*/

#include <fstream>
#include "filepath.h"
#include "frame_reader.h"
#include "iowrapper.h"
#include "glossary.h"
#include "simul.h"


void help(std::ostream& os)
{
    os << "Syntax:\n";
    os << "        sweet CLASS [DIRECTORY] [INPUTFILE] [binary=0]\n";
    os << "Synopsis: exports Cytosim's object coordinates to binary or text files.\n";
    os << "Each frame of the trajectory file is sent to a separate file.\n";
    os << "CLASS names the objects to be exported. Supported values:\n";
    os << "        fiber : export all fibers\n";
    os << "The binary format follows the `Sweet20` layout:\n";
    os << "        [2 bytes, unsigned integer: class]\n";
    os << "        [2 bytes, unsigned integer: info/color]\n";
    os << "        [4 bytes, unsigned integer: identity]\n";
    os << "        [4 bytes, float: X coordinate]\n";
    os << "        [4 bytes, float: Y coordinate]\n";
    os << "        [4 bytes, float: Z coordinate]\n";
    os << "With `binary=0` specificed, text files are generated, in the same layout\n";
    os << "This is " << DIM << "D\n";
}


FILE * openFile(const char base[], unsigned inx, bool binary)
{
    char name[256] = { 0 };
    FILE * f = nullptr;
    
    if ( binary )
    {
        snprintf(name, sizeof(name), "%s%04u.sweet", base, inx);
        f = fopen(name, "wb");
    }
    else
    {
        snprintf(name, sizeof(name), "%s%04u.txt", base, inx);
        f = fopen(name, "w");
    }
    if ( !f )
        std::cerr << "Error: could not create `" << name << "'\n";
    if ( f && ferror(f) )
    {
        fclose(f);
        std::cerr << "Error making `" << name << "'\n";
        f = nullptr;
    }
    return f;
}


//------------------------------------------------------------------------------
#pragma mark - write data chunk


void writeBinary(FILE* file, uint16_t a, uint16_t b, uint32_t c, Vector const& pos)
{
    fwrite(&a, 2, 1, file);
    fwrite(&b, 2, 1, file);
    fwrite(&c, 4, 1, file);
    float vec[3] = { 0 };
    pos.store(vec);
    fwrite(vec, 3, sizeof(float), file);
}


void writeText(FILE* file, uint16_t a, uint16_t b, uint32_t c, Vector2 const& pos)
{
    fprintf(file, "%i %i %i ", a, b, c);
    fprintf(file, "%.6f %.6f 0\n", pos.XX, pos.YY);
}

void writeText(FILE* file, uint16_t a, uint16_t b, uint32_t c, Vector3 const& pos)
{
    fprintf(file, "%i %i %i ", a, b, c);
    fprintf(file, "%.6f %.6f %.6f\n", pos.XX, pos.YY, pos.ZZ);
}


//------------------------------------------------------------------------------
#pragma mark -

void writeFibers(FILE* file, bool binary, FiberSet const& fibers)
{
    // process fibers in the natural order:
    for ( Fiber const* fib = fibers.firstID(); fib; fib = fibers.nextID(fib) )
    {
        uint16_t a = fib->prop->number();
        uint16_t b = 0;
        uint32_t c = fib->identity();
        if ( a != fib->prop->number() || c != fib->identity() )
            fprintf(stderr, "Warning: Sweet20 data format overflow\n");
        if ( binary )
        {
            for ( size_t i = 0; i < fib->nbPoints(); ++i )
                writeBinary(file, a, b, c, fib->posPoint(i));
        }
        else
        {
            for ( size_t i = 0; i < fib->nbPoints(); ++i )
                writeText(file, a, b, c, fib->posPoint(i));
        }
    }
}

//------------------------------------------------------------------------------
#pragma mark -

int main(int argc, char* argv[])
{
    if ( argc < 2 || strstr(argv[1], "help") )
    {
        help(std::cout);
        return EXIT_SUCCESS;
    }
    
    std::string what = argv[1];
    if ( what != "fiber" )
    {
        help(std::cout);
        return EXIT_SUCCESS;
    }

    Simul simul;
    Glossary arg;
    FrameReader reader;
    bool binary = 1;

    if ( arg.read_strings(argc-2, argv+2) )
        return EXIT_FAILURE;
    
    if ( arg.has_key("directory") )
        FilePath::change_dir(arg.value("directory"));

    arg.set(binary, "binary");
    std::string input = Simul::TRAJECTORY;
    arg.set(input, ".cmo") || arg.set(input, "input");

    reader.openFile(input);
    
    if ( reader.badFile() )
    {
        fprintf(stderr, "could not open input file\n");
        return EXIT_FAILURE;
    }
    
    try
    {
        unsigned frame = 0;
        simul.loadProperties();
        // process all frames of the trajectory:
        while ( 0 == reader.loadNextFrame(simul) )
        {
            FILE* file = openFile(what.c_str(), frame, binary);
            if ( file )
            {
                writeFibers(file, binary, simul.fibers);
                fclose(file);
            }
            ++frame;
        }
    }
    catch( Exception & e )
    {
        std::cerr << e.brief() << '\n';
        return EXIT_FAILURE;
    }
}
